# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 187ad36646d77f7b2da6a9b5531ce562b5e057223da81d54a9cd4b87d0be00b812f73dd0cb8226636da66cf749290071ec33b790dff1213a05805a813cf78c54

test:
  secret_key_base: f05e17098211ae16fb6fcb579c45569e4e50b2fd5d9ecd9421d74673fe97c53b5a51c76cac0e1f12e8366957ac1e15193f657324b83bad9fb20ac29c56724e49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
